name: Build documentation
description: Update README.org if there is a change in the API or version

on:
  workflow_call:
    input:
      commit_message:
        type: string
        required: true
        description: Commit message for updating documentation

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # Import GPG key for signing of commits
        # https://github.com/crazy-max/ghaction-import-gpg
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

        # Install Emacs onto system
      - name: Install Emacs
        run: sudo apt install emacs-nox --yes

        # Parse VERSION for master branch
      - name: Cleanup VERSION
        if: ${{ github.ref == "/refs/heads/master" }}
        run: echo "::set-output name=PRE_RELEASE::$(cat VERSION)"
        run: echo "$(cat VERSION | cut -d '-' -f 1)" > VERSION
        run: echo "::set-output name=RELEASE::$(cat VERSION)"
        id: version

        # Parse CHANGELOG for master branch
      - name: Cleanup CHANGELOG
        needs: version
        if: ${{ github.ref == "/refs/heads/master" }}
        run: >
          sed -i \
          "s/${{ steps.version.outputs.PRE_RELEASE }}\
          /${{steps.version.outputs.RELEASE }} [$(date +%F)]/" \
          CHANGELOG.org

        # Run shell script to populate the README file
      - name: Update README.org
        run: .github/scripts/doc-builder.sh

        # Publish changes to the current branch using my bot
        # https://github.com/EndBug/add-and-commit
      - name: Publish new docs
        uses: EndBug/add-and-commit@v9
        with:
          add:
            - "README.org"
            - "VERSION"
            - "CHANGELOG.org"
          message: ${{ inputs.commit_message }}
          author_name: arifer612-bot
          author_email: 103842184+arifer612-bot@users.noreply.github.com
          committer_name: arifer612-bot
          committer_email: 103842184+arifer612-bot@users.noreply.github.com
          push: true
