name: Pre-release
Description: CI/CD to run before full releases

on:
  push:
    branches: master
  pull-request:
    branches: master

concurrency:
  group: ci-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-flaker:
    uses: |
      "${{ github.repository }}/.github/workflows/_flaker.yml@master"

  call-builder:
    uses: |
      "${{ github.repository }}/.github/workflows/_build.docs.yml@master"
    with:
      commit_message: "Bump VERSION and update changes to README and CHANGELOG"
